## Adapt this file to your current configuration
name: Cypress Tests
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
